version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: DockerFile
    container_name: dewtech-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www/

  nginx:
    image: nginx:1.25.1-alpine-slim
    container_name: dewtech-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
